- heading: Web Development
  short-description: lorem temporibus ipsa! Necessitatibus quibusdam ut blanditiis molestias perspiciatis dolorem quae autem illum cumque.
  button-text: learn more
  button-link: /index.html
  image: https://images.unsplash.com/photo-1541560052-5e137f229371?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  alt:
- heading: Copywriting
  short-description: lorem temporibus ipsa! Necessitatibus quibusdam ut blanditiis molestias perspiciatis dolorem quae autem illum cumque.
  button-text: learn more
  button-link: /index.html
  image: https://images.unsplash.com/photo-1541560052-5e137f229371?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  alt:
- heading: Social Media
  short-description: lorem temporibus ipsa! Necessitatibus quibusdam ut blanditiis molestias perspiciatis dolorem quae autem illum cumque.
  button-text: learn more
  button-link: /index.html
  image: https://images.unsplash.com/photo-1541560052-5e137f229371?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  alt: